---
uiStyle:
  blankList:
    classes: [list]
    background: ""
    item:
      normal: ""
      hover: ""
      selected: ""
      drag: ""
      innerBorder: [ 0, 0, 0, 0 ]
    innerBorder: [ 0, 0, 0, 0 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    scrollBorder: [ 50, 55, 50, 50 ]
    selectionChangedSound: ""
    label: { font: Roboto Regular, size: 36, colour: "#FFFFFF" }
    selectedLabel: { font: Roboto Regular, size: 36, colour: "#FFFFFF" }
    disabledLabel: { font: Roboto Regular, size: 36, colour: "#FFFFFF" }
    gap: 50

  systemList:
    classes: [list]
    background: ""
    item:
      normal: ""
      hover: ""
      selected: ""
      drag: ""
      innerBorder: [ 24, 24, 24, 24 ]
    innerBorder: [ 2, 2, 2, 2 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    scrollBorder: [ 50, 55, 50, 50 ]
    selectionChangedSound: ""
    label: { font: Roboto Regular, size: 48, colour: "#FFFFFF" }
    selectedLabel: { font: Roboto Regular, size: 48, colour: "#FFFFFF" }
    disabledLabel: { font: Roboto Regular, size: 48, colour: "#FFFFFF" }
    gap: 50

  gameList:
    classes: [list]
    background: ""
    item:
      normal: ""
      hover: ""
      selected: ""
      drag: ""
      innerBorder: [ 24, 0, 24, 0 ]
    innerBorder: [ 2, 2, 2, 2 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    scrollBorder: [ 0, 0, 0, 0 ]
    selectionChangedSound: ""
    label: { font: Roboto Regular, size: 48, colour: "#FFFFFF" }
    selectedLabel: { font: Roboto Regular, size: 48, colour: "#FFFFFF" }
    disabledLabel: { font: Roboto Regular, size: 48, colour: "#FFFFFF" }
    gap: 50

  textMenu:
    classes: [list]
    background: ""
    item:
      normal: { img: "ui/text_menu_item.png", colour: "#747474" }
      hover: { img: "ui/text_menu_item.png", colour: "#747474" }
      selected: { img: "ui/text_menu_item_selected.png", colour: "#FF5353" }
      drag: ""
      innerBorder: [ 40, 24, 40, 24 ]
    innerBorder: [ 2, 2, 2, 2 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    scrollBorder: [ 0, 0, 0, 0 ]
    selectionChangedSound: ""
    label: { font: Roboto Regular, size: 70, colour: "#FFFFFF" }
    selectedLabel: { font: Roboto Regular, size: 70, colour: "#FFFFFF" }
    disabledLabel: { font: Roboto Regular, size: 70, colour: "#747474" }
    gap: 22

  labelHeader:
    classes: [label]
    label: { font: Roboto Regular, size: 90, colour: "#FFFFFF" }

  labelRegular:
    classes: [label]
    label: { font: Roboto Regular, size: 48, colour: "#FFFFFF" }
    
  labelDescription:
    classes: [label]
    label: { font: Roboto Regular, size: 48, colour: "#FFFFFF" }

  labelTag:
    classes: [label]
    label: { font: Roboto Regular, size: 48, colour: "#000000" }
    
  labelListEntry:
    classes: [label]
    label: { font: Roboto Regular, size: 48, colour: "#FFFFFF", shadowDistance: 5, shadowSmoothness: 10, shadowColour: "#000000" }

  rgScrollbar:
    classes: [scrollbar]
    horizontalBorder: [ 60, 0, 0, 0]
    verticalBorder: [0, 60, 0, 0]
    bar:
      horizontal: { img: ui/scrollbar.png, colour: "#FFFFFF" }
      vertical: { img: ui/scrollbar.png, colour: "#FFFFFF" }
    thumb:
      normal: { img: ui/scrollbar_thumb.png, colour: "#FFFFFF" }
      down: { img: ui/scrollbar_thumb.png, colour: "#FFFFFF" }
      hover: { img: ui/scrollbar_thumb.png, colour: "#FFFFFF" }
      disabled: { img: ui/scrollbar_thumb.png, colour: "#FFFFFF" }
      innerBorder: [ 0, 0, 0, 0 ]
      upSound: ""
      downSound: ""
      hoverSound: ""
