---
uiStyle:
  blankList:
    classes: [list]
    background: ""
    item:
      normal: ""
      hover: ""
      selected: ""
      drag: ""
      innerBorder: [ 0, 0, 0, 0 ]
    innerBorder: [ 0, 0, 0, 0 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    scrollBorder: [ 50, 50, 50, 50 ]
    selectionChangedSound: ""
    label: { font: Roboto Regular, size: 36, colour: "#FFFFFF" }
    selectedLabel: { font: Roboto Regular, size: 36, colour: "#FFFFFF" }
    disabledLabel: { font: Roboto Regular, size: 36, colour: "#FFFFFF" }
    gap: 50

  gridList:
    classes: [list]
    background: ""
    item:
      normal: { img: "ui/grid_item.png", colour: "#FFFFFF" }
      hover: { img: "ui/grid_item.png", colour: "#FFFFFF" }
      selected: { img: "ui/grid_item_selected.png", colour: "#EE595A" }
      drag: ""
      innerBorder: [ 24, 24, 24, 24 ]
    innerBorder: [ 2, 2, 2, 2 ]
    extraMouseBorder: [ 1, 1, 1, 1 ]
    scrollBorder: [ 200, 100, 200, 100 ]
    selectionChangedSound: ""
    label: { font: Roboto Regular, size: 36, colour: "#FFFFFF" }
    selectedLabel: { font: Roboto Regular, size: 36, colour: "#FFFFFF" }
    disabledLabel: { font: Roboto Regular, size: 36, colour: "#FFFFFF" }
    gap: 50

  labelHeader:
    classes: [label]
    label: { font: Roboto Regular, size: 96, colour: "#FFFFFF" }

  labelRegular:
    classes: [label]
    label: { font: Roboto Regular, size: 48, colour: "#FFFFFF" }
    
  labelDescription:
    classes: [label]
    label: { font: Roboto Regular, size: 44, colour: "#FFFFFF" }
    
  labelListEntry:
    classes: [label]
    label: { font: Roboto Regular, size: 35, colour: "#FFFFFF" }

  rgScrollbar:
    classes: [scrollbar]
    horizontalBorder: [ 60, 0, 0, 0]
    verticalBorder: [0, 60, 0, 0]
    bar:
      horizontal: { img: ui/scrollbar.png, colour: "#FFFFFF" }
      vertical: { img: ui/scrollbar.png, colour: "#FFFFFF" }
    thumb:
      normal: { img: ui/scrollbar_thumb.png, colour: "#FFFFFF" }
      down: { img: ui/scrollbar_thumb.png, colour: "#FFFFFF" }
      hover: { img: ui/scrollbar_thumb.png, colour: "#FFFFFF" }
      disabled: { img: ui/scrollbar_thumb.png, colour: "#FFFFFF" }
      innerBorder: [ 0, 0, 0, 0 ]
      upSound: ""
      downSound: ""
      hoverSound: ""
