---

en-GB:
  gen1arcade: 1st Generation Arcade
  gen2arcade: 2nd Generation Arcade
  gen3arcade: 3rd Generation Arcade
  gen4arcade: 4th Generation Arcade
  gen5arcade: 5th Generation Arcade
  gen6arcade: 6th Generation Arcade
  gen7arcade: 7th Generation Arcade
  gen8arcade: 8th Generation Arcade
  gen1console: 1st Generation Consoles
  gen2console: 2nd Generation Consoles
  gen3console: 3rd Generation Consoles
  gen4console: 4th Generation Consoles
  gen5console: 5th Generation Consoles
  gen6console: 6th Generation Consoles
  gen7console: 7th Generation Consoles
  gen8console: 8th Generation Consoles
  gen4handheld: 4th Generation Handhelds
  gen5handheld: 5th Generation Handhelds
  gen6handheld: 6th Generation Handhelds
  gen7handheld: 7th Generation Handhelds
  gen8handheld: 8th Generation Handhelds
  arcade: Arcade
  console: Console
  handheld: Handheld
  computer: Computer

...