---

en-GB:
  gen1: 1st Generation
  gen2: 2nd Generation
  gen3: 3rd Generation
  gen4: 4th Generation
  gen5: 5th Generation
  gen6: 6th Generation
  gen7: 7th Generation
  gen8: 8th Generation
  gen9: 9th Generation
  arcade: Arcade
  console: Console
  handheld: Handheld
  computer: Computer

...