bezels:
  - id: gameboy
    defaultZoom: 0.5
    images:
    - image: bezels/dmg-bg.png
      displayCentre: [85, 78]
      baseScale: 1
      layer: background
    - image: bezels/dmg-border-square-4x.png
      displayCentre: [3200, 1600]
      baseScale: 4
      layer: foreground
  - id: gameboy-pocket
    defaultZoom: 0.5
    images:
    - image: bezels/pocket-bg.png
      displayCentre: [85, 78]
      baseScale: 1
      layer: background
    - image: bezels/pocket-border-square-4x.png
      displayCentre: [3200, 1600]
      baseScale: 4
      layer: foreground
  - id: gameboy-color
    defaultZoom: 0.5
    images:
    - image: bezels/color-border-square-4x.png
      displayCentre: [3200, 1600]
      baseScale: 4
      layer: foreground
  - id: gameboy-advance
    defaultZoom: 0.5
    images:
    - image: bezels/gba-border-square-8x.png
      displayCentre: [3200, 1600]
      baseScale: 8
      layer: foreground
  - id: ndsi
    defaultZoom: 0.75
    images:
    - image: bezels/dsi-border-square-4x-90.png
      displayCentre: [3200, 1600]
      baseScale: 4
      layer: foreground
    coreOptions:
      desmume:
        desmume_screens_gap: 90
