cores:
  - id: bsnes
  - id: snes9x
  - id: fbneo
  - id: genesis_plus_gx
  - id: parallel_n64
    options:
      parallel-n64-gfxplugin: angrylion
      parallel-n64-pak1: memory
  - id: swanstation
  - id: mgba
  - id: gambatte
  - id: mednafen_gba
  - id: desmume
    options:
      desmume_num_cores: 4
  - id: kronos
    options:
      kronos_videocoretype: opengl_cs
  - id: mednafen_saturn
  - id: pcsx2
    options:
      pcsx2_renderer: D3D11
    blockedExtensions: [cue]
  - id: dolphin
    options:
      dolphin_renderer: Hardware
  - id: mupen64plus_next
  - id: stella
  - id: mesen
  - id: nestopia