mappings:
  - id: n64
    physicalToLibretro:
      a: b
      b: 'y'
      start: start
      dpup: dpup
      dpdown: dpdown
      dpleft: dpleft
      dpright: dpright
      ltrigger: l
      rtrigger: r
      ztrigger: l2
      cleft: -rightx
      cright: +rightx
      cup: -righty
      cdown: +righty
      leftx: leftx
      lefty: lefty
    controllers:
      n64:
        physicalToSDL:
          a: 'a'
          b: 'b'
          start: start
          dpup: dpup
          dpdown: dpdown
          dpleft: dpleft
          dpright: dpright
          ltrigger: leftshoulder
          rtrigger: rightshoulder
          ztrigger: lefttrigger
          cleft: -rightx
          cright: +rightx
          cup: -righty
          cdown: +righty
          leftx: leftx
          lefty: lefty
  - id: megadrive
    physicalToLibretro:
      a: 'y'
      b: b
      c: a
      x: l
      y: x
      z: r
      start: start
      mode: select
      dpup: dpup
      dpdown: dpdown
      dpleft: dpleft
      dpright: dpright
      leftx: leftx
      lefty: lefty
    controllers:
      sega:
        physicalToSDL:
          a: 'a'
          b: 'b'
          c: righttrigger
          x: 'x'
          y: 'y'
          z: rightshoulder
          start: start
          mode: back
          dpup: dpup
          dpdown: dpdown
          dpleft: dpleft
          dpright: dpright
          leftx: leftx
          lefty: lefty
  - id: saturn
    physicalToLibretro:
      a: b
      b: a
      c: r
      x: 'y'
      y: x
      z: l
      l: l2
      r: r2
      start: start
      mode: back
      dpup: dpup
      dpdown: dpdown
      dpleft: dpleft
      dpright: dpright
      leftx: leftx
      lefty: lefty
    controllers:
      sega:
        physicalToSDL:
          a: 'a'
          b: 'b'
          c: righttrigger
          x: 'x'
          y: 'y'
          z: rightshoulder
          l: leftshoulder
          r: lefttrigger
          start: start
          mode: back
          dpup: dpup
          dpdown: dpdown
          dpleft: dpleft
          dpright: dpright
          leftx: leftx
          lefty: lefty
