systems:
  - id: atari2600
    regions: 
      - name: Atari 2600
        region: [world]
    cores: [stella]
    manufacturer: Atari
    releaseDate: 1977-09-11
    generation: 2
    category: console
    screenFilters: [crt-rf-3phase]

  - id: nes
    regions: 
      - name: Nintendo Entertainment System
        region: [world]
      - name: Famicom
        region: [jp]
    cores: [nestopia, mesen]
    manufacturer: Nintendo
    releaseDate: 1983-07-15
    generation: 3
    category: console
    screenFilters: [crt-composite-ntsc-3phase]
  - id: snes
    regions: 
      - name: Super Nintendo Entertainment System
        region: [world]
      - name: Super Famicom
        region: [jp]
    cores: [snes9x, bsnes]
    manufacturer: Nintendo
    releaseDate: 1990-11-21
    generation: 4
    category: console
    screenFilters: [crt-composite-ntsc-3phase]
  - id: n64
    regions:
      - name: Nintendo 64
        region: [world]
    cores: [mupen64plus_next, parallel_n64]
    manufacturer: Nintendo
    releaseDate: 1996-06-23
    generation: 5
    category: console
    screenFilters: [crt-svideo]
  - id: gamecube
    regions:
      - name: GameCube
        region: [world]
    cores: [dolphin]
    manufacturer: Nintendo
    releaseDate: 2001-09-14
    generation: 6
    category: console
    screenFilters: [crt-svideo]

  - id: gb
    regions:
      - name: Game Boy
        region: [world]
    cores: [gambatte]
    manufacturer: Nintendo
    releaseDate: 1989-04-21
    generation: 4
    category: handheld
    screenFilters: [lcd-gameboy-pocket, lcd-gameboy, lcd-gameboy-color]
    bezels: [gameboy-pocket, gameboy]
  - id: gbc
    regions:
      - name: Game Boy Color
        region: [world]
    cores: [gambatte]
    manufacturer: Nintendo
    releaseDate: 1998-10-21
    generation: 5
    category: handheld
    screenFilters: [lcd-gameboy-color]
    bezels: [gameboy-color]
  - id: gba
    regions:
      - name: Game Boy Advance
        region: [world]
    cores: [mgba, mednafen_gba]
    manufacturer: Nintendo
    releaseDate: 2001-03-21
    generation: 6
    category: handheld
    screenFilters: [lcd-gameboy-advance]
    bezels: [gameboy-advance]
  - id: nds
    regions:
      - name: Nintendo DS
        region: [world]
    cores: [melonds, desmume]
    manufacturer: Nintendo
    releaseDate: 2004-11-21
    generation: 7
    category: handheld
    screenFilters: [lcd-ds]
    bezels: [ndsi]

  - id: mastersystem
    regions:
      - name: Master System
        region: [world]
    cores: [genesis_plus_gx]
    manufacturer: Sega
    releaseDate: 1985-10-20
    generation: 3
    category: console
    screenFilters: [crt-composite-ntsc-3phase]
  - id: megadrive
    regions:
      - name: Mega Drive
        region: [world]
      - name: Sega Genesis
        region: [us]
    cores: [genesis_plus_gx]
    manufacturer: Sega
    releaseDate: 1988-10-29
    generation: 4
    category: console
    screenFilters: [crt-composite-ntsc-2phase-megadrive, crt-composite-ntsc-2phase]
  - id: megacd
    regions:
      - name: Mega CD
        region: [world]
      - name: Sega CD
        region: [us, br]
    cores: [genesis_plus_gx]
    manufacturer: Sega
    releaseDate: 1991-12-12
    generation: 4
    category: console
    screenFilters: [crt-composite-ntsc-2phase-megadrive, crt-composite-ntsc-2phase]
  - id: saturn
    regions:
      - name: Saturn
        region: [world]
    cores: [mednafen_saturn]
    manufacturer: Sega
    releaseDate: 1994-11-22
    generation: 5
    category: console
    screenFilters: [crt-svideo]

  - id: gamegear
    regions:
      - name: Game Gear
        region: [world]
    cores: [genesis_plus_gx]
    manufacturer: Sega
    releaseDate: 1990-10-06
    generation: 4
    category: handheld
    screenFilters: [lcd-grid]

  - id: psx
    regions:
      - name: PlayStation
        region: [world]
    cores: [swanstation]
    manufacturer: Sony
    releaseDate: 1994-12-03
    generation: 5
    category: console
    screenFilters: [crt-svideo]
  - id: ps2
    regions:
      - name: PlayStation 2
        region: [world]
    cores: [pcsx2]
    manufacturer: Sony
    releaseDate: 2000-03-04
    generation: 6
    category: console
    screenFilters: [crt-svideo]

  - id: neogeo
    regions:
      - name: Neo Geo
        region: [world]
    cores: [fbneo]
    manufacturer: SNK
    releaseDate: 1990-04-26
    generation: 4
    category: arcade
    screenFilters: [crt-rgb]
  - id: cps1
    regions:
      - name: CP System I
        region: [world]
    cores: [fbneo]
    manufacturer: Capcom
    releaseDate: 1988-05-13
    generation: 4
    category: arcade
    screenFilters: [crt-rgb]
  - id: cps2
    regions:
      - name: CP System II
        region: [world]
    cores: [fbneo]
    manufacturer: Capcom
    releaseDate: 1993-09-10
    generation: 4
    category: arcade
    screenFilters: [crt-rgb]
  - id: cps3
    regions:
      - name: CP System III
        region: [world]
    cores: [fbneo]
    manufacturer: Capcom
    releaseDate: 1996-10-23
    generation: 4
    category: arcade
    screenFilters: [crt-rgb]
