systems:
  # Computer
  - id: msdos
    regions:
      - name: MS-DOS
        region: [world]
    cores: [dosbox]
    manufacturer: Microsoft
    releaseDate: 1981
    category: computer
    unitsSold: 150000000
    screenFilters: [crt-rgb]
  - id: zx
    regions:
      - name: ZX Spectrum
        region: [world]
    cores: []
    manufacturer: Sinclair
    releaseDate: 1982-04-23
    category: computer
    unitsSold: 5000000
    screenFilters: [crt-rf]
  - id: c64
    regions:
      - name: Commodore 64
        region: [world]
    cores: []
    manufacturer: Commodore
    releaseDate: 1982-08
    category: computer
    unitsSold: 15000000
    screenFilters: [crt-composite-ntsc-2phase]
  - id: amiga
    regions:
      - name: Amiga
        region: [world]
    cores: []
    manufacturer: Commodore
    releaseDate: 1985
    category: computer
    unitsSold: 4850000
    screenFilters: [crt-composite-ntsc-2phase]
  - id: msx
    regions:
      - name: MSX
        region: [world]
    cores: []
    manufacturer: ASCII
    releaseDate: 1983-10-21
    category: computer
    unitsSold: 9000000
    screenFilters: [crt-composite-ntsc-2phase]

  # 1st Generation

  # 2nd Generation
  - id: atari2600
    regions: 
      - name: Atari 2600
        region: [world]
    cores: [stella]
    manufacturer: Atari
    releaseDate: 1977-09-11
    generation: 2
    category: console
    unitsSold: 30000000
    screenFilters: [crt-rf-3phase]
  - id: atari5200
    regions: 
      - name: Atari 5200
        region: [world]
    cores: []
    manufacturer: Atari
    releaseDate: 1982-05-21
    generation: 2
    category: console
    unitsSold: 1400000
    screenFilters: [crt-rf-3phase]
  - id: colecovision
    regions: 
      - name: ColecoVision
        region: [world]
    cores: []
    manufacturer: Coleco
    releaseDate: 1982-08
    generation: 2
    category: console
    unitsSold: 2000000
    screenFilters: [crt-rf-3phase]
  - id: intellivision
    regions: 
      - name: Intellivision
        region: [world]
    cores: []
    manufacturer: Mattel
    releaseDate: 1979
    generation: 2
    category: console
    unitsSold: 3000000
    screenFilters: [crt-rf-3phase]
  - id: odyssey2
    regions: 
      - name: Odyssey 2
        region: [world]
    cores: []
    manufacturer: Magnavox
    releaseDate: 1978-09
    generation: 2
    category: console
    unitsSold: 2000000
    screenFilters: [crt-rf-3phase]

  # 3rd Generation
  - id: nes
    regions: 
      - name: Nintendo Entertainment System
        region: [world]
      - name: Famicom
        region: [jp]
    cores: [nestopia, mesen]
    manufacturer: Nintendo
    releaseDate: 1983-07-15
    generation: 3
    category: console
    unitsSold: 61910000
    screenFilters: [crt-composite-ntsc-3phase]
  - id: mastersystem
    regions:
      - name: Master System
        region: [world]
    cores: [genesis_plus_gx]
    manufacturer: Sega
    releaseDate: 1985-10-20
    generation: 3
    category: console
    unitsSold: 13000000
    screenFilters: [crt-composite-ntsc-3phase]
  - id: atari7800
    regions:
      - name: Atari 7800
        region: [world]
    cores: []
    manufacturer: Atari
    releaseDate: 1986-05-01
    generation: 3
    category: console
    unitsSold: 3770000
    screenFilters: [crt-rf-3phase]

  # 4th Generation Consoles
  - id: snes
    regions: 
      - name: Super Nintendo Entertainment System
        region: [world]
      - name: Super Famicom
        region: [jp]
    cores: [snes9x, bsnes]
    manufacturer: Nintendo
    releaseDate: 1990-11-21
    generation: 4
    category: console
    unitsSold: 49100000
    screenFilters: [crt-composite-ntsc-3phase]
  - id: megadrive
    regions:
      - name: Mega Drive
        region: [world]
      - name: Sega Genesis
        region: [us]
    cores: [genesis_plus_gx]
    manufacturer: Sega
    releaseDate: 1988-10-29
    generation: 4
    category: console
    unitsSold: 30750000
    screenFilters: [crt-composite-ntsc-2phase-megadrive, crt-composite-ntsc-2phase]
  - id: megacd
    regions:
      - name: Mega CD
        region: [world]
      - name: Sega CD
        region: [us, br]
    cores: [genesis_plus_gx]
    manufacturer: Sega
    releaseDate: 1991-12-12
    generation: 4
    category: console
    unitsSold: 2240000
    screenFilters: [crt-composite-ntsc-2phase-megadrive, crt-composite-ntsc-2phase]
  - id: pcengine
    regions:
      - name: PC Engine
        region: [world]
      - name: TurboGrafx-16
        region: [us]
    cores: []
    manufacturer: NEC
    releaseDate: 1987-10-30
    generation: 4
    category: console
    unitsSold: 5620000
    screenFilters: [crt-composite-ntsc-2phase]
  - id: cdi
    regions:
      - name: CD-i
        region: [world]
    cores: []
    manufacturer: Philips
    releaseDate: 1991-10-03
    generation: 4
    category: console
    unitsSold: 1000000
    screenFilters: [crt-composite-ntsc-2phase]

  # 4th Generation Handhelds
  - id: gb
    regions:
      - name: Game Boy
        region: [world]
    cores: [gambatte]
    manufacturer: Nintendo
    releaseDate: 1989-04-21
    generation: 4
    category: handheld
    unitsSold: 70000000
    screenFilters: [lcd-gameboy-pocket, lcd-gameboy, lcd-gameboy-color]
    bezels: [gameboy-pocket, gameboy]
  - id: gamegear
    regions:
      - name: Game Gear
        region: [world]
    cores: [genesis_plus_gx]
    manufacturer: Sega
    releaseDate: 1990-10-06
    generation: 4
    category: handheld
    unitsSold: 11000000
    screenFilters: [lcd-grid]
  - id: lynx
    regions:
      - name: Lynx
        region: [world]
    cores: []
    manufacturer: Atari
    releaseDate: 1989-09-01
    generation: 4
    category: handheld
    unitsSold: 2000000
    screenFilters: [lcd-grid]
  - id: pcenginegt
    regions:
      - name: PC Engine GT
        region: [world]
      - name: TurboExpress
        region: [us]
    cores: []
    manufacturer: NEC
    releaseDate: 1990-12-01
    generation: 4
    category: handheld
    unitsSold: 1500000
    screenFilters: [lcd-grid]

  # 4th Generation Arcade
  - id: neogeo
    regions:
      - name: Neo Geo
        region: [world]
    cores: [fbneo]
    manufacturer: SNK
    releaseDate: 1990-04-26
    generation: 4
    category: arcade
    screenFilters: [crt-rgb]
  - id: cps1
    regions:
      - name: CP System I
        region: [world]
    cores: [fbneo]
    manufacturer: Capcom
    releaseDate: 1988-05-13
    generation: 4
    category: arcade
    screenFilters: [crt-rgb]
  - id: cps2
    regions:
      - name: CP System II
        region: [world]
    cores: [fbneo]
    manufacturer: Capcom
    releaseDate: 1993-09-10
    generation: 4
    category: arcade
    screenFilters: [crt-rgb]
  - id: cps3
    regions:
      - name: CP System III
        region: [world]
    cores: [fbneo]
    manufacturer: Capcom
    releaseDate: 1996-10-23
    generation: 4
    category: arcade
    screenFilters: [crt-rgb]
  - id: tunit
    regions:
      - name: T Unit
        region: [world]
    cores: []
    manufacturer: Midway
    releaseDate: 1992
    generation: 4
    category: arcade
    screenFilters: [crt-rgb]
  - id: wolfunit
    regions:
      - name: Wolf Unit
        region: [world]
    cores: []
    manufacturer: Midway
    releaseDate: 1994
    generation: 4
    category: arcade
    screenFilters: [crt-rgb]

  # 5th Generation Consoles
  - id: n64
    regions:
      - name: Nintendo 64
        region: [world]
    cores: [mupen64plus_next, parallel_n64]
    manufacturer: Nintendo
    releaseDate: 1996-06-23
    generation: 5
    category: console
    unitsSold: 32930000
    screenFilters: [crt-svideo]
  - id: 32x
    regions:
      - name: 32X
        region: [world]
    cores: []
    manufacturer: Sega
    releaseDate: 1994-11-21
    generation: 5
    category: console
    unitsSold: 665000
    screenFilters: [crt-composite-ntsc-2phase-megadrive, crt-composite-ntsc-2phase]
  - id: saturn
    regions:
      - name: Saturn
        region: [world]
    cores: [mednafen_saturn]
    manufacturer: Sega
    releaseDate: 1994-11-22
    generation: 5
    category: console
    unitsSold: 9260000
    screenFilters: [crt-svideo]
  - id: jaguar
    regions: 
      - name: Jaguar
        region: [world]
    cores: []
    manufacturer: Atari
    releaseDate: 1993-11-23
    generation: 5
    category: console
    unitsSold: 250000
    screenFilters: [crt-svideo]
  - id: psx
    regions:
      - name: PlayStation
        region: [world]
    cores: [swanstation]
    manufacturer: Sony
    releaseDate: 1994-12-03
    generation: 5
    category: console
    unitsSold: 102490000
    screenFilters: [crt-svideo]
  - id: 3do
    regions:
      - name: 3DO
        region: [world]
    cores: []
    manufacturer: 3DO
    releaseDate: 1993-10-04
    generation: 5
    category: console
    unitsSold: 2000000
    screenFilters: [crt-svideo]

  # 5th Generation Handhelds
  - id: gbc
    regions:
      - name: Game Boy Color
        region: [world]
    cores: [gambatte]
    manufacturer: Nintendo
    releaseDate: 1998-10-21
    generation: 5
    category: handheld
    unitsSold: 48690000
    screenFilters: [lcd-gameboy-color]
    bezels: [gameboy-color]
  - id: virtualboy
    regions:
      - name: Virtual Boy
        region: [world]
    cores: []
    manufacturer: Nintendo
    releaseDate: 1995-07-21
    generation: 5
    category: handheld
    unitsSold: 770000
    screenFilters: [lcd-grid]
  - id: nomad
    regions:
      - name: Nomad
        region: [world]
    cores: [genesis_plus_gx]
    manufacturer: Sega
    releaseDate: 1995-10-01
    generation: 5
    category: handheld
    unitsSold: 1000000
    screenFilters: [lcd-grid]
  - id: ngp
    regions:
      - name: Neo Geo Pocket
        region: [world]
    cores: []
    manufacturer: SNK
    releaseDate: 1998-10-28
    generation: 5
    category: handheld
    unitsSold: 100000
    screenFilters: [lcd-grid]
  - id: ngpc
    regions:
      - name: Neo Geo Pocket Color
        region: [world]
    cores: []
    manufacturer: SNK
    releaseDate: 1999-03-16
    generation: 5
    category: handheld
    unitsSold: 2000000
    screenFilters: [lcd-grid]

  # 5th Generation Arcade
  - id: model2
    regions:
      - name: Model 2
        region: [world]
    cores: []
    manufacturer: Sega
    releaseDate: 1994-03
    generation: 5
    category: arcade
    screenFilters: [crt-rgb]
  - id: model3
    regions:
      - name: Model 3
        region: [world]
    cores: []
    manufacturer: Sega
    releaseDate: 1996-07-26
    generation: 5
    category: arcade
    screenFilters: [crt-rgb]

  # 6th Generation Consoles
  - id: gamecube
    regions:
      - name: GameCube
        region: [world]
    cores: [dolphin]
    manufacturer: Nintendo
    releaseDate: 2001-09-14
    generation: 6
    category: console
    unitsSold: 21740000
    screenFilters: [crt-svideo]
  - id: dreamcast
    regions:
      - name: Dreamcast
        region: [world]
    cores: []
    manufacturer: Sega
    releaseDate: 1998-11-27
    generation: 6
    category: console
    unitsSold: 9130000
    screenFilters: [crt-svideo]
  - id: ps2
    regions:
      - name: PlayStation 2
        region: [world]
    cores: [pcsx2]
    manufacturer: Sony
    releaseDate: 2000-03-04
    generation: 6
    category: console
    unitsSold: 155000000
    screenFilters: [crt-svideo]
  - id: xbox
    regions:
      - name: Xbox
        region: [world]
    cores: []
    manufacturer: Microsoft
    releaseDate: 2001-11-15
    generation: 6
    category: console
    unitsSold: 24000000
    screenFilters: [crt-svideo]

  # 6th Generation Handhelds
  - id: gba
    regions:
      - name: Game Boy Advance
        region: [world]
    cores: [mgba, mednafen_gba]
    manufacturer: Nintendo
    releaseDate: 2001-03-21
    generation: 6
    category: handheld
    unitsSold: 81510000
    screenFilters: [lcd-gameboy-advance]
    bezels: [gameboy-advance]
  - id: wonderswan
    regions:
      - name: WonderSwan
        region: [world]
    cores: []
    manufacturer: Bandai
    releaseDate: 1999-03-04
    generation: 6
    category: handheld
    unitsSold: 1550000
    screenFilters: [lcd-grid]
    bezels: []
  - id: wonderswancolor
    regions:
      - name: WonderSwan Color
        region: [world]
    cores: []
    manufacturer: Bandai
    releaseDate: 2000-12-09
    generation: 6
    category: handheld
    unitsSold: 1100000
    screenFilters: [lcd-grid]
    bezels: []

  # 6th Generation Arcade
  - id: naomi
    regions:
      - name: NAOMI
        region: [world]
    cores: []
    manufacturer: Sega
    releaseDate: 1998-11-20
    generation: 6
    category: arcade
    screenFilters: [crt-rgb]
  - id: atomiswave
    regions:
      - name: Atomiswave
        region: [world]
    cores: []
    manufacturer: Sammy
    releaseDate: 2003-04
    generation: 6
    category: arcade
    screenFilters: [crt-rgb]

  # 7th Generation Consoles

  # 7th Generation Handhelds
  - id: nds
    regions:
      - name: Nintendo DS
        region: [world]
    cores: [melonds, desmume]
    manufacturer: Nintendo
    releaseDate: 2004-11-21
    generation: 7
    category: handheld
    unitsSold: 154000000
    screenFilters: [lcd-ds]
    bezels: [ndsi]
  - id: psp
    regions:
      - name: PlayStation Portable
        region: [world]
    cores: []
    manufacturer: Sony
    releaseDate: 2004-12-12
    generation: 7
    category: handheld
    unitsSold: 81000000
    screenFilters: [lcd-grid]
    bezels: []

  # 8th Generation Consoles

  # 8th Generation Handhelds

  
  # 9th Generation Consoles

  # 9th Generation Handhelds
