systems:
  - id: snes
    regions: 
      - name: Super Nintendo Entertainment System
        region: [world]
      - name: Super Famicom
        region: [jp]
    cores: [snes9x]
    manufacturer: Nintendo
    releaseDate: 1990-11-21
  - id: megadrive
    regions:
      - name: Mega Drive
        region: [world]
      - name: Sega Genesis
        region: [us]
    cores: [genesis_plus_gx]
    manufacturer: Sega
    releaseDate: 1988-10-29
  - id: psx
    regions:
      - name: PlayStation
        region: [world]
    cores: [swanstation]
    manufacturer: Sony
    releaseDate: 1994-12-03
  - id: neogeo
    regions:
      - name: Neo Geo
        region: [world]
    cores: [fbneo]
    manufacturer: SNK
    releaseDate: 1990-04-26
  - id: cps2
    regions:
      - name: CP System II
        region: [world]
    cores: [fbneo]
    manufacturer: Capcom
    releaseDate: 1993-09-10
  - id: n64
    regions:
      - name: Nintendo 64
        region: [world]
    cores: [parallel_n64]
    manufacturer: Nintendo
    releaseDate: 1996-06-23

